### ISSUE TITLE
请教数据格式

### ISSUE THREAD

**Issue by xiaokc** [jasonwbw/AnswerRanker_of_FRONTIER_LAB#1]
论文中提到使用的数据格式是，每条数据（session）包含4句话: 一轮context(Q0+A0), 当前query和上下文感知的response，但readme中数据格式没有限制sentence的个数？还没看具体代码，刚好打开看到这行。。

**Comment by jasonwbw** [comment]
@xiaokc 是的，按照这个代码实验是需要按照4句话排列的，只是模型讲道理是对输入条数不敏感的（代码可能需要修改）。

**Comment by xiaokc** [comment]
明白了，理论上多轮对话Context个数也是可以任意多个的，不过论文实验中只用了一轮Context，谢谢回复

**Comment by jasonwbw** [comment]
不客气
